### ISSUE TITLE
A resource removed from a dataset should disappear in a reasonable amount of time when going through the `Edit fiscal data schema` flow

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#150] opened 2021-02-22 19:39 UTC
When I click on `Edit fiscal data schema` in the dashboard and click on `Remove` next to a resource, I expect this resource to disappear from the list of resources and changes to be propagated to GitHub so I can confidently know I can remove more resources or add new ones without leaving the dataset in a "broken" state.

## Acceptance

* [x] Once a resource has been removed from a dataset after clicking on `Edit fiscal data schema`, I see it disappear from the list of resources and can see that the `datapackage.json` file was updated in a timely manner.

## Tasks

* [ ] ...

## Analysis

* Related to #149: There is a delay for pushing updates to GitHub which can be a few minutes up to more than 30 minutes (maximum delay to be confirmed). This prevents users from adding/removing new resources to an existing dataset.

**Comment by sglavoie** [comment] 2021-02-22 19:49
Note: The same will also be true when adding resources. There is a delay which means that a user can add a resource, go back to the dashboard, click on the dataset to add a new resource and see that the newest resource added is not shown in the list of resources until the actual commit shows up on GitHub.

**Comment by rufuspollock** [comment] 2021-02-23 13:36
@sglavoie sounds good. One clarification: the removal (or addition) should only happen *at* the end of the process when you save i think ...

**Comment by cotts** [comment] 2021-02-23 13:54
We can check on https://vercel.com/docs/platform/limits if there is something that can impact the performance and also review the code to see if there is any blocking request there is any performance issue/blocking workflow.

**Comment by risenW** [comment] 2021-02-23 13:57
BLOCKED: There's a delay when saving/updating the dataset on GitHub from the portal API. This delay takes a variable (btw 5-20 mins) amount of time. 

Possible reasons:
* Vercel API function delay ??

**Comment by risenW** [comment] 2021-02-25 08:29
FIXED: This issue has been fixed in the latest deployed version of Portal. For reference, see this pull https://github.com/datopian/gift-portal/pull/154

The issue was caused by not using ES6 promises in our API calls, this made tracking of upload/saving state inconsistent.

**Closed by risenW** 2021-02-25 08:29 UTC
Labels: bug
